global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus-standalone:9091']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'minio'
    static_configs:
      - targets: ['milvus-minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  - job_name: 'etcd'
    static_configs:
      - targets: ['milvus-etcd:2379']
    metrics_path: '/metrics'
    scrape_interval: 30s